version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - /srv/dev-disk-by-uuid-bafd8995-3fbf-427d-b4a2-8bf9a1fdb866/gooseberry-home/frontend:/app
    networks:
      - gooseberry-home-network

  backend:
    build: ./backend
    ports:
      - "3001:8080"
    volumes:
      - /srv/dev-disk-by-uuid-bafd8995-3fbf-427d-b4a2-8bf9a1fdb866/gooseberry-home/backend:/app
    networks:
      - gooseberry-home-network

networks:
  gooseberry-home-network: