version: '3.8'

services:
  frontend:
    build: ./frontend/gooseberry-home-frontend
      - "3000:80"
    volumes:
      - ./frontend/gooseberry-home-frontend:/app
    networks:
      - gooseberry-home-network

  backend:
    build: ./backend
    ports:
      - "3001:8080"
    volumes:
      - ./backend:/app
    networks:
      - gooseberry-home-network

networks:
  gooseberry-home-network:
