services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    networks:
      - gooseberry-home-network

  backend:
    build: ./backend
    ports:
      - "3001:8080"
    #volumes:
    #  - ./backend:/app
    networks:
      - gooseberry-home-network

networks:
  gooseberry-home-network:
